# Generated by Django 6.0.7 on 2026-07-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_alter_profile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
