# Generated by Django 6.0.7 on 2026-07-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_profile_preferred_category'),
        ('recommender', '0005_application_cover_letter'),
    ]

    operations = [
    ]
