# Generated by Django 6.0.7 on 2026-07-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_add_jobview_model'),
        ('recommender', '0007_alter_application_applied_at_and_more'),
    ]

    operations = [
    ]
