# Generated by Django 6.0.7 on 2026-07-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_merge_20260728_1246'),
        ('recommender', '0008_merge_20260728_1734'),
    ]

    operations = [
    ]
