# Generated by Django 6.0.7 on 2026-07-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_merge_20260728_1825'),
        ('recommender', '0009_merge_20260729_0223'),
    ]

    operations = [
    ]
