# Generated by Django 6.0.7 on 2026-07-30 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_merge_20260730_1747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('degree', 'Degree Certificate'), ('transcript', 'Academic Transcript'), ('certification', 'Professional Certification'), ('id', 'National ID / Passport'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, help_text="Optional label, e.g. 'BSc Computer Science Degree'", max_length=150)),
                ('file', models.FileField(upload_to='qualification_documents/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('verification_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_documents', to='recommender.profile')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Recruiter who last reviewed this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_qualification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='attached_documents',
            field=models.ManyToManyField(blank=True, help_text='Qualification documents the applicant chose to submit with this specific application.', related_name='applications', to='recommender.qualificationdocument'),
        ),
        migrations.AddIndex(
            model_name='qualificationdocument',
            index=models.Index(fields=['profile', 'verification_status'], name='recommender_profile_3d15f9_idx'),
        ),
    ]
