# Generated by Django 6.0.7 on 2026-08-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_merge_20260729_2059'),
        ('recommender', '0011_qualificationdocument_application_attached_documents_and_more'),
    ]

    operations = [
    ]
